import type { StrategySpec } from './strategy.types';

export const perfBenchStrategy: StrategySpec = {
  name: 'perf-bench',
  description: 'p50/p95/p99 latency benchmarking on full-scale data',
  env: 'staging',
  includeCategories: ['reference', 'identity', 'organization', 'people', 'clinical', 'operational'],
  counts: {
    clinics: 100,
    doctors: 400,
    patients: 10000,
    consultations: 20000,
    appointments: 6000,
    historicalDaysBack: 30,
  },
  anonymize: false,
  snapshotAfter: true,
  snapshotName: 'perf-bench',
  parallelExec: true,
  dryRunFirst: false,
  stopOnError: false,
  compensateOnFailure: false,
  maxDurationMinutes: 15,
  memoryBudgetMb: 2048,
  expectedScenarioCount: 20000,
};

export const regressionStrategy: StrategySpec = {
  name: 'regression',
  description: 'Nightly CI regression — locked seed for byte-identical reruns',
  env: 'test',
  includeCategories: ['reference', 'identity', 'organization', 'people', 'clinical'],
  counts: {
    clinics: 10,
    doctors: 20,
    patients: 100,
    consultations: 200,
    appointments: 60,
    historicalDaysBack: 7,
  },
  anonymize: false,
  snapshotAfter: false,
  parallelExec: false,
  dryRunFirst: false,
  stopOnError: true,
  compensateOnFailure: true,
  masterSeedOverride: 4242,
  maxDurationMinutes: 3,
  memoryBudgetMb: 512,
  expectedScenarioCount: 200,
};

export const recoveryStrategy: StrategySpec = {
  name: 'recovery',
  description: 'Disaster-recovery snapshot restore (no fresh seeding, snapshot-only)',
  env: 'staging',
  includeCategories: ['reference'],
  counts: {
    clinics: 0,
    doctors: 0,
    patients: 0,
    consultations: 0,
    appointments: 0,
    historicalDaysBack: 0,
  },
  anonymize: false,
  snapshotAfter: false,
  parallelExec: false,
  dryRunFirst: false,
  stopOnError: true,
  compensateOnFailure: false,
  maxDurationMinutes: 5,
  memoryBudgetMb: 512,
  expectedScenarioCount: 0,
};
