// apps/web/lib/csp/inline-hashes.ts
// AUTO-GENERATED by scripts/build-inline-hashes.ts. DO NOT EDIT BY HAND.
// Regenerate via: pnpm --filter web run build:hashes
// Last generated: 2026-05-13T18:51:33.265Z

/**
 * Whitelisted SHA-256 hashes of inline <script type="application/ld+json">
 * blocks on static pages. Each hash is added to the static-route CSP's
 * script-src directive (apps/web/next.config.ts and apps/web/lib/csp/policy.ts).
 *
 * The browser computes SHA-256 of each inline script's text content and
 * allows execution only if the result matches one of these hashes.
 */
export const INLINE_SCRIPT_HASHES: readonly string[] = [
  // homepage:organization
  'sha256-y/iw3wcpKoLATJMgs8PhoaRGbQDnea8jTyIzeGtGbwY=',
  // legal:privacy:webpage
  'sha256-hubuF8XNZYWaoNH5Lwoy9yyMjlNcqRPkXoyRgIG9oUc=',
  // legal:terms:webpage
  'sha256-Fw7j0+rEW+IfsIx5ouCrtf5Eht69i3eVpYJnumNvVyY=',
  // legal:cookies:webpage
  'sha256-eMl7+LIt0TqIPphPms/HvRzLV0KUmm/Cooovc3h1YII=',
  // legal:dpdp-notice:webpage
  'sha256-rAgjfIm0duBltPeGFAFq0roMm+7eVSdeJ0z6fTTxXgI=',
];

export const __INLINE_HASHES_MANAGED_BY__ = 'scripts/build-inline-hashes.ts' as const;
