// apps/web/lib/csp/policy.ts
// ═══════════════════════════════════════════════════════════════
// CSP POLICY BUILDER — Nonce-only architecture (Task #45, Phase 3)
//
// ARCHITECTURE (CTO decision Day 17, supersedes the hybrid nonce/hash model):
//   EVERY HTML route receives a nonce-based CSP. A cryptographically secure
//   128-bit nonce is generated per request in apps/web/proxy.ts and emitted
//   in `script-src 'nonce-...'`.
//
// WHY NONCE-ONLY (and not the previous hybrid hash/nonce split)?
//   The hybrid model classified marketing/legal pages as "static" and gave
//   them a hash-based CSP whose hash registry covered only the inline
//   JSON-LD blocks. But Next.js App Router emits its OWN inline bootstrap
//   scripts (`self.__next_f.push(...)` streaming-RSC chunks) on EVERY page,
//   static or not. Those framework scripts are not JSON-LD, their content
//   changes per build, and `'strict-dynamic'` makes the browser ignore the
//   host allowlist — so on a hash-only route they were all blocked.
//
//   The fix is the path Next.js officially supports: a per-request nonce.
//   When the CSP header carries `'nonce-...'`, Next.js automatically applies
//   that nonce to every framework `<script>` it renders. One mechanism,
//   one mental model, no build-time hash registry to keep in sync.
//
//   Note: inline `<script type="application/ld+json">` blocks are DATA, not
//   executable script — browsers never run them, so `script-src` never
//   evaluates them and they need neither a hash nor a nonce.
//
// STRICT-DYNAMIC RATIONALE:
//   `'strict-dynamic'` tells modern browsers: "if a script carries my nonce,
//    treat the scripts IT inserts as trusted too." This lets a nonced
//    bootstrap script (e.g. Next.js's loader) pull in `/_next/static/...`
//    chunks without each chunk URL needing to be in `script-src`.
//
//   IMPORTANT: when `'strict-dynamic'` is present, modern browsers IGNORE
//   the host allowlist in `script-src`. The allowlist is retained ONLY for
//   CSP Level 1 / legacy browsers (Safari < 15.4). Modern browsers rely on
//   nonce + strict-dynamic exclusively. This is INTENTIONAL.
//
// MODE FLIP (Phase 2 → Phase 3):
//   `mode: 'report-only'` → emits Content-Security-Policy-Report-Only header
//   `mode: 'enforce'`     → emits Content-Security-Policy header
//   Same policy content — only the header name differs.
//
// Pattern: Next.js official strict-CSP guide, Stripe strict-CSP,
//          Google web.dev/strict-csp, MDN CSP best practices (2026).
// ═══════════════════════════════════════════════════════════════

import {
  SCRIPT_SRC_ORIGINS,
  STYLE_SRC_ORIGINS,
  FONT_SRC_ORIGINS,
  IMG_SRC_ORIGINS,
  CONNECT_SRC_ORIGINS,
  FRAME_SRC_ORIGINS,
  REPORT_ENDPOINT_URL,
} from './allowed-origins';
import { assertHeaderSize, HeaderSizeLevel } from './header-size-guard';

/** CSP enforcement mode. */
export type CspMode = 'enforce' | 'report-only';

/** Input options to build a CSP header. */
export interface BuildCspOptions {
  /** Policy mode — controls which response header to use. */
  mode: CspMode;

  /** Per-request nonce — required. Generated by proxy.ts via generateNonce(). */
  nonce: string;

  /**
   * Override report endpoint for tests.
   * Production always uses `REPORT_ENDPOINT_URL` from allowed-origins.ts.
   */
  reportEndpoint?: string;
}

/** Resulting CSP header — name + value pair, ready to set on response. */
export interface CspHeader {
  /** HTTP header name (`Content-Security-Policy` or `...-Report-Only`). */
  name: 'Content-Security-Policy' | 'Content-Security-Policy-Report-Only';

  /** Header value (the full directives string). */
  value: string;

  /**
   * Size class — emitted by length guard.
   * `'ok' | 'warning' | 'error'` — caller can log warnings without throwing.
   */
  sizeLevel: HeaderSizeLevel;
}

/**
 * Build a complete CSP header from policy inputs.
 *
 * @throws Error if `nonce` is missing or empty.
 *
 * @example
 *   const { name, value } = buildCspHeader({
 *     mode: 'enforce',
 *     nonce: generateNonce(),
 *   });
 *   response.headers.set(name, value);
 */
export function buildCspHeader(opts: BuildCspOptions): CspHeader {
  if (!opts.nonce) {
    throw new Error('CSP build: a per-request nonce is required');
  }

  const reportUri = opts.reportEndpoint ?? REPORT_ENDPOINT_URL;

  // ── script-src ─────────────────────────────────────────────────
  // Strategy: 'self' + 'strict-dynamic' + 'nonce-...' + hosts (legacy fallback)
  //
  // 'unsafe-inline' is ABSENT — that's the whole point.
  // 'unsafe-eval' is ABSENT — no eval() in production code.
  // ─────────────────────────────────────────────────────────────
  const scriptSrcParts: string[] = [
    "'self'",
    "'strict-dynamic'",
    `'nonce-${opts.nonce}'`,
  ];

  // Legacy host allowlist — IGNORED by modern browsers when strict-dynamic is
  // present. Kept for CSP Level 1 fallback (Safari < 15.4, very old Chrome).
  for (const origin of SCRIPT_SRC_ORIGINS) scriptSrcParts.push(origin);

  // 'https:' fallback for absolute legacy browsers — they ignore the rest.
  scriptSrcParts.push('https:');

  // ── style-src ──────────────────────────────────────────────────
  // 'unsafe-inline' allowed for styles because:
  //   - Next.js inlines critical CSS at build time
  //   - shadcn/ui injects runtime style attributes (style="--foo: bar")
  //   - style-src-attr directive doesn't support nonces at all (CSP spec gap)
  //
  // STYLE injection attacks are FAR less severe than script injection:
  //   - Can't exfiltrate data (no JS access)
  //   - Can't redirect users
  //   - Worst case: visual defacement
  //
  // Pattern: Next.js docs explicitly recommend 'unsafe-inline' for styles
  // even in strict CSP setups. Stripe, Linear, Vercel — all do the same.
  // ─────────────────────────────────────────────────────────────
  const styleSrcParts: string[] = ["'self'", "'unsafe-inline'", ...STYLE_SRC_ORIGINS];

  // ── img-src ────────────────────────────────────────────────────
  // `data:` for inline SVGs / base64 thumbnails (next/image generates these).
  // `blob:` for client-generated images (photo preview before upload).
  // ─────────────────────────────────────────────────────────────
  const imgSrcParts: string[] = ["'self'", 'data:', 'blob:', ...IMG_SRC_ORIGINS];

  // ── font-src ───────────────────────────────────────────────────
  const fontSrcParts: string[] = ["'self'", 'data:', ...FONT_SRC_ORIGINS];

  // ── connect-src ────────────────────────────────────────────────
  // Includes API, Sentry ingest, analytics endpoints.
  // 'self' covers same-origin XHR (next.js Server Actions, internal /api).
  // ─────────────────────────────────────────────────────────────
  const connectSrcParts: string[] = ["'self'", ...CONNECT_SRC_ORIGINS];

  // ── frame-src ──────────────────────────────────────────────────
  // Empty in v2 (no payment integrations yet). Razorpay (#53) will add.
  // ─────────────────────────────────────────────────────────────
  const frameSrcParts: string[] = ["'self'", ...FRAME_SRC_ORIGINS];

  // ── worker-src ─────────────────────────────────────────────────
  // Service workers (PWA, future). `blob:` for inline workers.
  // ─────────────────────────────────────────────────────────────
  const workerSrcParts: string[] = ["'self'", 'blob:'];

  // ── Build the directive string ─────────────────────────────────
  const directives: string[] = [
    `default-src 'self'`,
    `script-src ${scriptSrcParts.join(' ')}`,
    `style-src ${styleSrcParts.join(' ')}`,
    `img-src ${imgSrcParts.join(' ')}`,
    `font-src ${fontSrcParts.join(' ')}`,
    `connect-src ${connectSrcParts.join(' ')}`,
    `frame-src ${frameSrcParts.join(' ')}`,
    `worker-src ${workerSrcParts.join(' ')}`,
    `manifest-src 'self'`,
    `media-src 'self'`,
    // Hard blocks — these CANNOT have any source.
    `object-src 'none'`, // No <object> / <embed> / <applet>
    `base-uri 'self'`, // <base href="..."> attacks blocked
    `form-action 'self'`, // Form posts can only go to our origin
    `frame-ancestors 'none'`, // No one can iframe our site (clickjack defense)
    // Force HTTP → HTTPS upgrade for ALL sub-resources.
    `upgrade-insecure-requests`,
    // Modern reporting (Reporting API).
    `report-to csp-endpoint`,
    // Legacy fallback (browsers that don't support report-to yet).
    `report-uri ${reportUri}`,
  ];

  const value = directives.join('; ');

  const sizeLevel = assertHeaderSize(value);

  const name: CspHeader['name'] =
    opts.mode === 'enforce' ? 'Content-Security-Policy' : 'Content-Security-Policy-Report-Only';

  return { name, value, sizeLevel };
}