// ═══════════════════════════════════════════════════════════════
// SHARED MEDIA TYPES — Task #46
//
// Type-only definitions used by web, api, and worker packages.
// No runtime code, no Prisma imports → keeps web bundle small.
// Importing this file from FE costs ~0 bytes (TypeScript erases types).
//
// Single source of truth for media kinds, variants, providers,
// moderation/scan status, DTOs exchanged across the wire, and
// branded ID types for compile-time safety.
//
// @see packages/db/prisma/schema.prisma — runtime models (MediaAsset)
// @see packages/shared/src/constants/media.constants.ts — runtime config
// @see packages/shared/src/validators/domains/media.schema.ts — Zod runtime validation
// ═══════════════════════════════════════════════════════════════

// ─── Branded ID types (compile-time safety) ────────────────────

declare const __mediaIdBrand: unique symbol;
/**
 * MediaAsset primary-key UUID — compile-time guarantee that arbitrary
 * strings are NOT passed where a MediaAsset id is expected.
 *
 * Create via `makeMediaId(uuid)` — never cast.
 */
export type MediaId = string & { readonly [__mediaIdBrand]: 'MediaId' };

declare const __r2StorageKeyBrand: unique symbol;
/**
 * R2 object key — the `s3://bucket/<key>` path inside the bucket.
 *
 * Examples:
 *   "consultations/<consultationUuid>/<mediaUuid>.jpg"
 *   "clinics/<clinicUuid>/cover/<mediaUuid>.jpg"
 *
 * Always built by the R2 provider — never user-supplied. The brand
 * prevents accidental concatenation of arbitrary user input.
 */
export type R2StorageKey = string & { readonly [__r2StorageKeyBrand]: 'R2StorageKey' };

declare const __cfImageIdBrand: unique symbol;
/** Cloudflare Images asset identifier (the path segment used in delivery URLs). */
export type CfImageId = string & { readonly [__cfImageIdBrand]: 'CfImageId' };

declare const __blurhashBrand: unique symbol;
/**
 * Blurhash string — typically 20–30 chars, base83-encoded.
 *
 * Decoded client-side to render a 32×32 pixel placeholder before
 * the real image streams in. See {@link https://blurha.sh}.
 */
export type Blurhash = string & { readonly [__blurhashBrand]: 'Blurhash' };

declare const __sha256HexBrand: unique symbol;
/** Lower-case 64-char SHA-256 hex digest, computed client-side from the blob. */
export type Sha256Hex = string & { readonly [__sha256HexBrand]: 'Sha256Hex' };

/**
 * Build a {@link MediaId} from an unverified string. Throws on bad input.
 *
 * UUIDv4 format (lower-case 36-char canonical) is enforced. The branded
 * return type signals to the type-checker that the caller has validated
 * the value at runtime.
 */
export function makeMediaId(value: string): MediaId {
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)) {
    throw new Error(`Invalid MediaId — expected canonical UUID, got: ${value}`);
  }
  return value.toLowerCase() as MediaId;
}

// ─── MediaKind — categorical taxonomy of media we store ────────

/**
 * Discriminator for every media artefact in the system.
 *
 * Each kind maps deterministically (via media.constants.ts) to:
 *   - bucket (private vs public)
 *   - allowed MIME types
 *   - per-entity upload limits
 *   - default retention policy
 *   - moderation flow
 *   - variant generation rules (aspect-preserve vs face-crop)
 *
 * MUST mirror the Prisma `MediaKind` enum exactly. Drift is caught by the
 * Prisma-enum mirror test in packages/shared/src/__tests__/validators.
 */
export type MediaKind =
  // ── PRIVATE: clinical PHI under DPDP (signed URLs, audit-logged) ──
  | 'CONSULTATION_PHOTO' // patient's intra-oral photo for AI triage
  | 'PRESCRIPTION_DOC' // prescription PDF / scanned Rx
  | 'USER_AVATAR' // patient profile picture (semi-private)
  // ── PUBLIC: marketing & content (direct CDN, SEO-indexable) ──
  | 'CLINIC_COVER' // partner clinic's hero/cover photo
  | 'CLINIC_GALLERY' // additional clinic interior photos
  | 'DOCTOR_AVATAR' // doctor profile picture (shown on booking pages)
  | 'BLOG_IMAGE' // article hero & figure images (Task #125)
  | 'OG_IMAGE' // social-share preview images (Task #106)
  | 'BRAND_ASSET'; // Datun logo, marketing graphics

/**
 * Privacy/access tier for a {@link MediaKind}. Drives bucket routing,
 * URL signing, CDN cache headers, and audit-logging behaviour.
 */
export type MediaAccessClass = 'private' | 'public';

// ─── Variants — what CF Images renders for delivery ────────────

/**
 * Display variants generated by Cloudflare Images.
 *
 * `ORIGIN` is the source-of-truth in R2 (never delivered to users directly
 * except via short-lived signed URLs for diagnostic re-processing).
 */
export type MediaVariant = 'THUMBNAIL' | 'MEDIUM' | 'LARGE' | 'ORIGIN';

/** Map of variant → resolved public URL (or signed URL for private kinds). */
export type MediaVariantUrls = Partial<Record<MediaVariant, string>>;

// ─── Provider — adapter behind StorageProvider interface ───────

/**
 * Concrete storage/delivery adapter that produced/serves this asset.
 *
 * R2 is the primary origin. CLOUDFLARE_IMAGES is the primary delivery
 * layer. CLOUDINARY is a documented fallback adapter (no single point of
 * failure — memory rule #27), only activated if the primary stack has a
 * sustained outage. MediaAssets created during a fallback window are
 * tagged `CLOUDINARY` so we can later migrate them.
 */
export type MediaProvider = 'R2' | 'CLOUDFLARE_IMAGES' | 'CLOUDINARY';

// ─── Moderation & scan status ──────────────────────────────────

/**
 * AI-moderation outcome for a media asset.
 *
 * PENDING  — queued, worker has not yet run moderation
 * APPROVED — AI says safe + on-topic (dental/oral for clinical kinds)
 * FLAGGED  — borderline / off-topic; needs human admin review
 * REJECTED — clearly NSFW / abusive; auto-soft-deleted, uploader notified
 */
export type MediaModerationStatus = 'PENDING' | 'APPROVED' | 'FLAGGED' | 'REJECTED';

/**
 * Static-analysis / virus-scan outcome. Placeholder pipeline for now —
 * wired so a third-party scanner (e.g., ClamAV) can plug in later
 * without schema change. CLEAN allows variant generation; INFECTED
 * triggers immediate purge from R2 + CF Images.
 */
export type MediaScanStatus = 'PENDING' | 'CLEAN' | 'INFECTED';

/**
 * Lifecycle state machine driven by the orchestrator service.
 *
 *   INITIATED → upload-intent issued; signed URL handed to client; row
 *               exists in DB but R2 object may not exist yet
 *   UPLOADED  → client confirmed direct R2 upload; worker job enqueued
 *   PROCESSING → worker is running EXIF strip / scan / moderation / variants
 *   READY     → all checks passed, variants available, safe to render
 *   REJECTED  → moderation REJECTED or scan INFECTED; soft-deleted
 *   FAILED    → permanent failure (corrupt bytes, provider error); admin retriable
 */
export type MediaLifecycleStatus =
  | 'INITIATED'
  | 'UPLOADED'
  | 'PROCESSING'
  | 'READY'
  | 'REJECTED'
  | 'FAILED';

// ─── DTOs exchanged over the wire ──────────────────────────────

/**
 * Payload returned by `POST /media/upload-intent`.
 *
 * Client uses {@link uploadUrl} + {@link formFields} to perform a direct
 * upload to R2 (no Datun-server bytes). After the PUT succeeds, client
 * calls `POST /media/:id/confirm` with the {@link mediaId} returned here.
 */
export interface UploadIntentResponse {
  /** UUID of the freshly-created MediaAsset row (status INITIATED). */
  readonly mediaId: MediaId;
  /** R2 presigned URL — single-use, time-limited. Method is always PUT. */
  readonly uploadUrl: string;
  /** Headers the client MUST send along with the PUT request. */
  readonly requiredHeaders: Readonly<Record<string, string>>;
  /** Maximum file size the upload URL will accept (enforced by R2 itself). */
  readonly maxBytes: number;
  /** Seconds until {@link uploadUrl} expires. */
  readonly ttlSeconds: number;
  /**
   * Storage key the object will land at in R2 (informational — client never
   * uses this for upload, but useful for client-side telemetry / debugging).
   */
  readonly storageKey: R2StorageKey;
  /** Echoed back so the client can sanity-check its own decision. */
  readonly kind: MediaKind;
}

/**
 * Payload sent by the client to `POST /media/:id/confirm` after a
 * successful direct upload to R2. The server uses these self-reported
 * metrics for analytics + the worker uses them to skip recomputation
 * (defensive — worker still verifies on its own).
 */
export interface ConfirmUploadPayload {
  /** Final byte length of the resized/encoded file the client actually pushed. */
  readonly finalSizeBytes: number;
  /** Output JPEG/WebP width in pixels. */
  readonly width: number;
  /** Output JPEG/WebP height in pixels. */
  readonly height: number;
  /** Client-computed blurhash. Worker may regenerate if absent or invalid. */
  readonly blurhash: Blurhash;
  /** Client-computed SHA-256 of the encoded blob — used for dedup-safe replays. */
  readonly sha256: Sha256Hex;
  /**
   * Original filename as the user selected it. Stored ONLY for audit
   * trails; NEVER trusted for type/extension decisions (magic-byte rules).
   */
  readonly originalFilename?: string;
}

/**
 * Public-facing read DTO. Returned by `GET /media/:id`, embedded in
 * Consultation / Clinic / Doctor responses, etc.
 *
 * URLs here are already resolved per-request:
 *   - public kinds → permanent CDN URLs (long cache)
 *   - private kinds → freshly-signed CF Images URLs with TTL
 */
export interface MediaAssetDTO {
  readonly id: MediaId;
  readonly kind: MediaKind;
  readonly accessClass: MediaAccessClass;
  readonly mimeType: string;
  readonly width: number | null;
  readonly height: number | null;
  readonly sizeBytes: number | null;
  readonly blurhash: Blurhash | null;
  readonly variants: MediaVariantUrls;
  readonly status: MediaLifecycleStatus;
  readonly moderation: MediaModerationStatus;
  /** ISO-8601 timestamps. */
  readonly createdAt: string;
  readonly processedAt: string | null;
}

/**
 * Reason payload for `DELETE /media/:id` — kept lightweight because the
 * actual deletion cascade is heavy (R2 origin + CF Images variants + DB
 * + audit log).
 */
export interface DeleteMediaPayload {
  /** Free-form human reason, redacted before write to AuditLog. */
  readonly reason: string;
  /**
   * If true, hard-purge from R2 + CF Images immediately. If false, only
   * soft-delete the DB row; physical purge runs on the retention cron.
   * DPDP `DeletionRequest` always sets this to true.
   */
  readonly hardPurge: boolean;
}

// ─── Type guards ───────────────────────────────────────────────

/** All MediaKind values — exported as a readonly tuple for runtime use. */
export const MEDIA_KINDS: readonly MediaKind[] = [
  'CONSULTATION_PHOTO',
  'PRESCRIPTION_DOC',
  'USER_AVATAR',
  'CLINIC_COVER',
  'CLINIC_GALLERY',
  'DOCTOR_AVATAR',
  'BLOG_IMAGE',
  'OG_IMAGE',
  'BRAND_ASSET',
] as const;

/** Narrow an unknown string into a MediaKind without throwing. */
export function isMediaKind(value: unknown): value is MediaKind {
  return typeof value === 'string' && (MEDIA_KINDS as readonly string[]).includes(value);
}

export const MEDIA_VARIANTS: readonly MediaVariant[] = [
  'THUMBNAIL',
  'MEDIUM',
  'LARGE',
  'ORIGIN',
] as const;

export function isMediaVariant(value: unknown): value is MediaVariant {
  return typeof value === 'string' && (MEDIA_VARIANTS as readonly string[]).includes(value);
}

export const MEDIA_PROVIDERS: readonly MediaProvider[] = [
  'R2',
  'CLOUDFLARE_IMAGES',
  'CLOUDINARY',
] as const;

export function isMediaProvider(value: unknown): value is MediaProvider {
  return typeof value === 'string' && (MEDIA_PROVIDERS as readonly string[]).includes(value);
}

// ─── Friendly-error i18n keys ──────────────────────────────────

/**
 * Translation keys used when the upload pipeline rejects a file.
 *
 * Memory rule (15 May 2026): user-facing copy NEVER blames the user and
 * NEVER mentions size. These keys redirect with an action-oriented message.
 * Frontend resolves them via `next-intl`. See apps/web/messages/<locale>/media.json.
 */
export const MEDIA_ERROR_KEYS = {
  /** First bytes don't match any allowed image signature (video, zip, exe …). */
  notAnImage: 'media.errors.notAnImage',
  /** Looks like a video file. */
  looksLikeVideo: 'media.errors.looksLikeVideo',
  /** File opens but is corrupted / unreadable. */
  cannotProcess: 'media.errors.cannotProcess',
  /** Per-consultation photo cap reached (5 by default). */
  consultationPhotoLimit: 'media.errors.consultationPhotoLimit',
  /** Per-clinic gallery cap reached. */
  galleryLimit: 'media.errors.galleryLimit',
  /** Upload window expired before client confirmed. */
  uploadExpired: 'media.errors.uploadExpired',
  /** Background processing failed — admin will retry. */
  processingFailed: 'media.errors.processingFailed',
} as const;

export type MediaErrorKey = (typeof MEDIA_ERROR_KEYS)[keyof typeof MEDIA_ERROR_KEYS];
