/**
 * generate-erd.ts — render the current database ERD as Mermaid markdown.
 *
 * Output: docs/architecture/database-erd.md
 *
 * Why Mermaid (not prisma-erd-generator):
 *   - Zero new dependencies
 *   - Renders natively in GitHub PRs
 *   - Diff-friendly (text format)
 *   - Investor / partner-shareable as-is
 *
 * Strategy: introspect Prisma's DMMF (data model meta format) and emit
 * a `erDiagram` block. Cardinality inferred from relation fields.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

async function getDmmf(): Promise<unknown> {
  const prismaInternals = (await import('@prisma/internals')) as unknown as {
    getDMMF: (args: { datamodelPath: string }) => Promise<{ datamodel: unknown }>;
  };
  const { datamodel } = await prismaInternals.getDMMF({
    datamodelPath: resolve('packages/db/prisma/schema.prisma'),
  });
  return datamodel;
}

interface DmmfModel {
  name: string;
  fields: Array<{
    name: string;
    type: string;
    kind: 'scalar' | 'object' | 'enum';
    isList: boolean;
    isRequired: boolean;
    relationName?: string;
    relationFromFields?: string[];
  }>;
}

interface DmmfDatamodel {
  models: DmmfModel[];
}

function emitMermaid(dm: DmmfDatamodel): string {
  const lines: string[] = ['erDiagram'];

  // Entities
  for (const model of dm.models) {
    lines.push(`  ${model.name} {`);
    for (const f of model.fields) {
      if (f.kind === 'object') continue; // relations rendered as edges
      const type = f.type;
      const optional = f.isRequired ? '' : ' "optional"';
      lines.push(`    ${type} ${f.name}${optional}`);
    }
    lines.push('  }');
  }

  // Relationships (one-to-many)
  const seen = new Set<string>();
  for (const model of dm.models) {
    for (const f of model.fields) {
      if (f.kind !== 'object') continue;
      if (!f.relationName) continue;
      const key = [model.name, f.type, f.relationName].sort().join('|');
      if (seen.has(key)) continue;
      seen.add(key);
      const cardinality = f.isList ? '}o--||' : '||--o{';
      lines.push(`  ${model.name} ${cardinality} ${f.type} : "${f.relationName}"`);
    }
  }

  return lines.join('\n');
}

async function main(): Promise<number> {
  console.log('Generating database ERD...');
  const datamodel = (await getDmmf()) as DmmfDatamodel;
  const mermaid = emitMermaid(datamodel);
  const md = `# Datun Database ERD

Auto-generated by \`generate-erd.ts\`. Do not edit manually — re-run the script.

\`\`\`mermaid
${mermaid}
\`\`\`
`;
  const outPath = resolve('docs/architecture/database-erd.md');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, md, 'utf8');
  console.log(`✓ Wrote ${outPath}`);
  return 0;
}

main()
  .then((code) => process.exit(code))
  .catch((err) => {
    console.error('generate-erd crashed:', err);
    process.exit(2);
  });
