/**
 * generate-rollback.ts — auto-generate ROLLBACK.sql skeleton.
 *
 * Reads a forward migration's SQL and produces a best-effort reverse SQL
 * file that the developer must review and complete.
 *
 * Reversal patterns:
 *   CREATE TABLE   → DROP TABLE IF EXISTS ... CASCADE
 *   ALTER TABLE ... ADD COLUMN  → ALTER TABLE ... DROP COLUMN
 *   CREATE INDEX   → DROP INDEX IF EXISTS
 *   CREATE TYPE    → DROP TYPE IF EXISTS ... CASCADE
 *   ADD CONSTRAINT → DROP CONSTRAINT IF EXISTS
 *
 * Patterns NOT auto-reversed (developer must handle):
 *   DROP statements (forward already destructive — manual restore needed)
 *   UPDATE statements (data changes — must hand-write reverse data ops)
 *   ALTER COLUMN type changes (data loss possible)
 *
 * Usage: tsx packages/db/src/scripts/generate-rollback.ts <migration-folder>
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';

interface ReverseStatement {
  forward: string;
  reverse: string | null;
  needsReview: boolean;
  note?: string;
}

function reverseStatement(stmt: string): ReverseStatement {
  const trimmed = stmt.trim();

  // CREATE TABLE
  const createTable = trimmed.match(/^CREATE TABLE\s+"(\w+)"/i);
  if (createTable) {
    return {
      forward: trimmed,
      reverse: `DROP TABLE IF EXISTS "${createTable[1]}" CASCADE;`,
      needsReview: false,
    };
  }

  // CREATE INDEX (with or without CONCURRENTLY/UNIQUE)
  const createIndex = trimmed.match(
    /^CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF NOT EXISTS\s+)?"(\w+)"/i,
  );
  if (createIndex) {
    return {
      forward: trimmed,
      reverse: `DROP INDEX IF EXISTS "${createIndex[1]}";`,
      needsReview: false,
    };
  }

  // CREATE TYPE (enum)
  const createType = trimmed.match(/^CREATE TYPE\s+"(\w+)"/i);
  if (createType) {
    return {
      forward: trimmed,
      reverse: `DROP TYPE IF EXISTS "${createType[1]}" CASCADE;`,
      needsReview: false,
    };
  }

  // ALTER TABLE ... ADD COLUMN
  const addColumn = trimmed.match(/^ALTER TABLE\s+"(\w+)"\s+ADD COLUMN\s+"(\w+)"/i);
  if (addColumn) {
    return {
      forward: trimmed,
      reverse: `ALTER TABLE "${addColumn[1]}" DROP COLUMN IF EXISTS "${addColumn[2]}";`,
      needsReview: false,
    };
  }

  // ALTER TABLE ... ADD CONSTRAINT
  const addConstraint = trimmed.match(/^ALTER TABLE\s+"(\w+)"\s+ADD CONSTRAINT\s+"(\w+)"/i);
  if (addConstraint) {
    return {
      forward: trimmed,
      reverse: `ALTER TABLE "${addConstraint[1]}" DROP CONSTRAINT IF EXISTS "${addConstraint[2]}";`,
      needsReview: false,
    };
  }

  // DROP statements — manual handling required
  if (/^(DROP|TRUNCATE)/i.test(trimmed)) {
    return {
      forward: trimmed,
      reverse: null,
      needsReview: true,
      note: 'Forward statement is destructive — restore from backup is the only safe reverse.',
    };
  }

  // UPDATE / DELETE / INSERT — data changes
  if (/^(UPDATE|DELETE|INSERT)/i.test(trimmed)) {
    return {
      forward: trimmed,
      reverse: null,
      needsReview: true,
      note: 'Data manipulation — write inverse data operation manually.',
    };
  }

  // ALTER COLUMN — type changes
  if (/^ALTER TABLE.*ALTER COLUMN/i.test(trimmed)) {
    return {
      forward: trimmed,
      reverse: null,
      needsReview: true,
      note: 'Column alteration — write reverse type cast manually.',
    };
  }

  return {
    forward: trimmed,
    reverse: null,
    needsReview: true,
    note: 'Unrecognized pattern — manual reverse required.',
  };
}

function splitStatements(sql: string): string[] {
  return sql
    .split(';')
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && !s.startsWith('--'));
}

function main(): number {
  const folder = process.argv[2];
  if (!folder) {
    console.error(
      'Usage: tsx generate-rollback.ts <migration-folder>\nExample: tsx generate-rollback.ts packages/db/prisma/migrations/20260520_add_clinic_subdomain',
    );
    return 1;
  }
  const migrationFile = join(folder, 'migration.sql');
  if (!existsSync(migrationFile)) {
    console.error(`Migration file not found: ${migrationFile}`);
    return 1;
  }

  const sql = readFileSync(migrationFile, 'utf8');
  const statements = splitStatements(sql);
  const reversed = statements.map(reverseStatement).reverse(); // dependency-reverse order

  const output: string[] = [
    `-- ROLLBACK.sql for ${basename(folder)}`,
    `-- Auto-generated by generate-rollback.ts`,
    `-- ⚠️  REVIEW EVERY LINE BEFORE TRUSTING`,
    '',
    'BEGIN;',
    '',
  ];

  for (const r of reversed) {
    if (r.reverse) {
      output.push(r.reverse);
    } else {
      output.push(`-- TODO MANUAL: ${r.note ?? 'review needed'}`);
      output.push(
        `-- Forward was: ${r.forward.slice(0, 120)}${r.forward.length > 120 ? '...' : ''}`,
      );
      output.push('-- (write reverse SQL here)');
      output.push('');
    }
  }

  output.push('');
  output.push('COMMIT;');

  const outputPath = join(folder, 'ROLLBACK.sql');
  writeFileSync(outputPath, output.join('\n'), 'utf8');

  const reviewCount = reversed.filter((r) => r.needsReview).length;
  console.log(`✓ Generated ${outputPath}`);
  console.log(`  ${reversed.length} statements processed`);
  console.log(`  ${reviewCount} require manual review (marked TODO MANUAL)`);
  return 0;
}

process.exit(main());
