// ═══════════════════════════════════════════════════════════════
// CONSULTATION CONTRACT — drives AI training data + analytics
// Field-aligned to real Consultation schema
// ═══════════════════════════════════════════════════════════════
import type { DataContract } from './contract.types';

export const CONSULTATION_CONTRACT: DataContract = {
  tableName: 'Consultation',
  version: '1.0.0',
  status: 'active',
  owner: 'datun-platform',
  consumers: ['datun-ai-triage', 'datun-fine-tune-pipeline', 'datun-admin-ui', 'datun-analytics'],
  fields: [
    {
      name: 'id',
      type: 'string',
      nullable: false,
      required: true,
      regex: '^[a-z0-9-]+$',
      maxLength: 64,
      piiClass: 'none',
      description: 'Stable consultation id (uuid)',
    },
    {
      name: 'patientId',
      type: 'string',
      nullable: false,
      required: true,
      maxLength: 64,
      piiClass: 'none',
      description: 'FK to Patient',
    },
    {
      name: 'userId',
      type: 'string',
      nullable: false,
      required: true,
      maxLength: 64,
      piiClass: 'none',
      description: 'FK to User',
    },
    {
      name: 'status',
      type: 'enum',
      nullable: false,
      required: true,
      enumValues: ['IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'CANCELLED'],
      piiClass: 'none',
      description: 'Lifecycle state',
    },
    {
      name: 'urgency',
      type: 'enum',
      nullable: true,
      required: false,
      enumValues: ['EMERGENCY', 'URGENT', 'MODERATE', 'ROUTINE'],
      piiClass: 'none',
      description: 'Wave 7 eval target — composite scoring weights this 0.25',
    },
    {
      name: 'chiefComplaint',
      type: 'string',
      nullable: true,
      required: false,
      minLength: 0,
      maxLength: 4000,
      piiClass: 'medium',
      description: 'Used for AI training; must respect Wave 5 anonymization.',
    },
    {
      name: 'language',
      type: 'string',
      nullable: false,
      required: true,
      maxLength: 16,
      piiClass: 'low',
      description: 'Locale code; defaults to "en"',
    },
    {
      name: 'promptVersion',
      type: 'string',
      nullable: true,
      required: false,
      regex: '^v\\d+\\.\\d+\\.\\d+$',
      piiClass: 'none',
      description: 'Required for prompt-rollback on regression.',
    },
    {
      name: 'safetyFlags',
      type: 'json',
      nullable: true,
      required: false,
      piiClass: 'none',
      description: 'Wave 12 guardrail output (violation list).',
    },
    {
      name: 'createdAt',
      type: 'datetime',
      nullable: false,
      required: true,
      piiClass: 'none',
      description: 'Freshness monitoring.',
    },
  ],
  freshness: { maxStaleSeconds: 1800, checkColumn: 'createdAt', severity: 'critical' },
  volume: { minRowsPerDay: 0, maxRowsPerDay: 50_000, severity: 'warning' },
  customRules: [
    'urgency=EMERGENCY MUST trigger guardrail check (Wave 12)',
    'promptVersion MUST exist in PromptVersion registry',
    'status transitions must be valid (IN_PROGRESS → COMPLETED/ABANDONED)',
  ],
  createdAt: '2026-05-05T00:00:00Z',
  updatedAt: '2026-05-05T00:00:00Z',
};
