// ═══════════════════════════════════════════════════════════════
// PATIENT TABLE CONTRACT — consumer-facing guarantee
// ═══════════════════════════════════════════════════════════════
import type { DataContract } from './contract.types';

export const PATIENT_CONTRACT: DataContract = {
  tableName: 'Patient',
  version: '1.0.0',
  status: 'active',
  owner: 'datun-platform',
  consumers: ['datun-ai-triage', 'datun-admin-ui', 'datun-analytics', 'datun-fine-tune-pipeline'],
  fields: [
    {
      name: 'id',
      type: 'string',
      nullable: false,
      required: true,
      regex: '^[a-z0-9_-]+$',
      minLength: 3,
      maxLength: 64,
      piiClass: 'none',
      description: 'Stable patient identifier',
    },
    {
      name: 'clinicId',
      type: 'string',
      nullable: false,
      required: true,
      regex: '^[a-z0-9-]+$',
      maxLength: 64,
      piiClass: 'none',
      description: 'Tenant scope. Required for cross-tenant blocker (Wave 6.1).',
    },
    {
      name: 'fullName',
      type: 'string',
      nullable: true,
      required: false,
      maxLength: 200,
      piiClass: 'high',
      description: 'Anonymized in DPDP profile via deterministic hash.',
    },
    {
      name: 'preferredLocale',
      type: 'enum',
      nullable: false,
      required: true,
      enumValues: [
        'hindi',
        'english',
        'punjabi',
        'bengali',
        'tamil',
        'telugu',
        'marathi',
        'gujarati',
      ],
      piiClass: 'low',
      description: 'Drives Claude system prompt locale selection.',
    },
    {
      name: 'ageYears',
      type: 'number',
      nullable: false,
      required: true,
      minValue: 0,
      maxValue: 120,
      piiClass: 'medium',
      description: 'Drives safety constraint logic (child<6, elderly).',
    },
    {
      name: 'gender',
      type: 'enum',
      nullable: false,
      required: true,
      enumValues: ['M', 'F', 'O'],
      piiClass: 'medium',
      description: 'Required for pregnancy gating.',
    },
    {
      name: 'aadhaar',
      type: 'string',
      nullable: true,
      required: false,
      regex: '^\\d{12}$',
      piiClass: 'critical',
      description: 'DPDP Section 4 — masked everywhere except encrypted column.',
    },
    {
      name: 'createdAt',
      type: 'datetime',
      nullable: false,
      required: true,
      piiClass: 'none',
      description: 'Used for freshness monitoring.',
    },
  ],
  freshness: { maxStaleSeconds: 3600, checkColumn: 'createdAt', severity: 'critical' },
  volume: { minRowsPerDay: 0, maxRowsPerDay: 100_000, severity: 'warning' },
  customRules: [
    'pregnancy flag MUST imply gender=F AND ageYears>=12 AND ageYears<=55',
    'safetyConstraints field child-under-6 MUST imply ageYears<=5',
    'aadhaar IF non-null MUST be encrypted at rest (column-level)',
  ],
  createdAt: '2026-05-05T00:00:00Z',
  updatedAt: '2026-05-05T00:00:00Z',
};
